image: cypress/browsers:node18.12.0-chrome107-ff107

pipelines:
  default:
    - step:
        name: Run Cypress Tests
        caches:
          - node
        script:
          - npm install
          - npm run cypress:run
