name: Run Industry Standards Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-industry-standards-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run specific Cypress test
        run: npx cypress run --spec "cypress/e2e/industryStandards.cy.js"
