name: Run Industry Standards Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-industry-standards-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run specific Cypress test
        run: npx cypress run --spec "cypress/e2e/industryStandards.cy.js"

